DELETE http://localhost:8080/api/configurations/646ab16259c4e05dd038f843
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBsZWNsYWlyIiwiaWQiOiI2NDZhNmY4ZWE2YTVkOGNkODVhMDU5Y2MiLCJpYXQiOjE2ODQ3MTQzOTgsImV4cCI6MTY4NDcxNzk5OH0.tK0GM1sqtUolZjMke9eaDoK7e3mpkrL7fkYMyxp5Pn0
